

   <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1><?php echo $this->text; ?></h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>
  
   <h1>Controller </h1>
  
   <h2>Object Collection from PHP Array</h2>
   
   <table class="table table-bordered">
            <tr>
                <th>Name</th>
                <th>Job</th>
                <th>Adress</th>
                <th>Salary</th>
            </tr>
            

     <?php
        
        foreach ($this->all as $person ) { 
                print '<tr>' ; 
                print '<td>'.$person->getName().'</td>' ; 
                print '<td>'.$person->getJob().'</td>' ; 
                print '<td>'.$person->getAdress().'</td>' ; 
                print '<td>'.$person->getSalary().'</td>' ; 
                print '</tr>' ; 
        }
     ?>
            
</table>
   
   
   <h2>Object Collection from DataBase Mysql </h2>
   
   <table class="table table-bordered">
            <tr>
                <th>MESSAGE LOG</th>
                <th>TYPE</th>
                <th>HOSTNAME</th>
                <th>LOCATION</th>
            </tr>
            

     <?php
        
        foreach ($this->res as $result ) { 
                print '<tr>' ; 
                print '<td>' ;  print $result['message'] ;  print '<td>' ; 
                print '<td>' ;  print $result['type']    ;  print '<td>' ; 
                print '<td>' ;  print $result['hostname'] ;  print '<td>' ; 
                print '<td>' ;  print $result['location'] ;  print '<td>' ; 
                print '</tr>' ; 
        }
     ?>
            
</table>